# -*- coding: utf-8 -*-
"""package_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNX1wuQHve6V2junbc5LOCqRklyGvcfV
"""

import tarfile
import os

def package_model(model_dir, output_dir):
    with tarfile.open(output_dir, 'w:gz') as tar:
        tar.add(model_dir, arcname=os.path.basename(model_dir))

package_model('/opt/ml/model', 'model.tar.gz')