# -*- coding: utf-8 -*-
"""tests/test_sample

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJfjUMo4SoqTxq5N0YAfliwS1Un9Yzmv
"""

import unittest

class TestSample(unittest.TestCase):
    def test_example(self):
        self.assertEqual(1, 1)

if __name__ == '__main__':
    unittest.main()