# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWpYXcCt9l79nrEtYkH303jP00qJbaqj
"""



import boto3
import sagemaker
from sagemaker.estimator import Estimator

# Define SageMaker session and role
sagemaker_session = sagemaker.Session()
role = 'arn:aws:iam::123456789012:role/SageMakerExecutionRole'

# Define the container image and hyperparameters
image = '123456789012.dkr.ecr.us-west-2.amazonaws.com/my-sagemaker-image:latest'
hyperparameters = {'epochs': 10, 'batch_size': 32}

# Create an Estimator
estimator = Estimator(
    image_uri=image,
    role=role,
    instance_count=1,
    instance_type='ml.m4.xlarge',
    hyperparameters=hyperparameters,
    output_path='s3://my-bucket/output'
)

# Start model training
estimator.fit({'train': 's3://my-bucket/data/train', 'test': 's3://my-bucket/data/test'})

